name:                yagbe
version:             0.1.0.0
github:              blueonyx/yagbe
license:             BSD-3-Clause
author:              martin hilbig
maintainer:          martin@mhilbig.de
copyright:           copyright (c) 2025 martin hilbig

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/blueonyx/yagbe#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- gtk3
- cairo
- time
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  yagbe-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - yagbe
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  yagbe-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - yagbe
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
